services:
  - type: web
    name: fortune-site-backend
    root: backend
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
