export {
  calcRouter,
  calcExpandedDivination,
  calcHonmeiStar,
  calcKyuseiProfile,
  calcLifePathNumber,
  calcNayin,
  calcNumerologyProfile,
  calcSanmei,
  calcSanmeiRelations,
  calcShichu,
  calcShichuResult,
  calcTenGod,
  calcTimingCycles,
  getSukuyo,
  KYUSEI_NAMES,
} from '../lib/divination/index.js'
